# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry',      '1.1.0'

  #ContentStartIndex
  # close source libs
  pod 'AgoraUIBaseViews/Source', :path => '../../../../apaas-common-libs-ios/AgoraUIBaseViews_Local.podspec'
  pod 'AgoraWidget/Source',      :path => '../../../../apaas-common-libs-ios/AgoraWidget_Local.podspec'
  
  # open source libs
  pod 'AgoraWidgets/Build', :path => '../../../AgoraWidgets_Local.podspec'
  #ContentEndIndex

  pod "Whiteboard",                 :git => 'https://github.com/netless-io/Whiteboard-iOS', :branch => 'effect-mixing'

  # post install, no signing for pods bundle, after xcode 14
  low_version_target_names = ["Armin", "YYModel", "Masonry", "NTLBridge", "CocoaLumberjack", "AliyunOSSiOS"]
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
	config.build_settings['ENABLE_BITCODE'] = 'NO'	

        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
        
        if low_version_target_names.include?(target.name)
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
      end
    end
  end
end

